// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLatestCents() {
  return window['go']['main']['App']['GetLatestCents']();
}

export function GetLatestNote() {
  return window['go']['main']['App']['GetLatestNote']();
}

export function GetLatestPitch() {
  return window['go']['main']['App']['GetLatestPitch']();
}

export function StartPitchDetection() {
  return window['go']['main']['App']['StartPitchDetection']();
}

export function StopPitchDetection() {
  return window['go']['main']['App']['StopPitchDetection']();
}
