// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLatestCents():Promise<number>;

export function GetLatestNote():Promise<string>;

export function GetLatestPitch():Promise<number>;

export function StartPitchDetection():Promise<string>;

export function StopPitchDetection():Promise<string>;
